### ISSUE TITLE
Cannot disable modul Vesta Common

### ISSUE THREAD

**Issue by ro-la** [vesta-webtrees-2-custom-modules/vesta_common#62] opened 2022-04-21 20:16 UTC
Trying to deactivate all Vesta modules there will be displayed a message "Modul Common deactivated" but the check box is still checked.

**Comment by ric2016** [comment] 2022-04-21 20:28
This was originally by design, see the module description: "This module cannot be disabled."
I decided to do it like this because 
* other Vesta modules depend on it and will not work if this module is disabled.
* disabling had no useful effect anyway. This is no longer the case as this module makes changes to the control panel.

I may have to rethink this. 
I am aware that this contradicts the advice to disable all custom modules when investigating bugs.
In the meantime, the workaround is to remove or rename the respective directory instead.

**Comment by ric2016** [comment] 2022-04-24 19:27
Fixed in latest release: Module may now be disabled.

**Closed by ric2016** 2022-04-24 19:27 UTC
